import 'package:sweet_bonanza_app/models/level_model.dart';

final List<String> elements = [
  'assets/images/find-pairs/1.png',
  'assets/images/find-pairs/2.png',
  'assets/images/find-pairs/3.png',
  'assets/images/find-pairs/4.png',
  'assets/images/find-pairs/5.png',
  'assets/images/find-pairs/6.png',
  'assets/images/find-pairs/7.png',
  'assets/images/find-pairs/8.png',
  'assets/images/find-pairs/9.png',
  'assets/images/find-pairs/10.png',
  'assets/images/find-pairs/11.png',
  'assets/images/find-pairs/12.png',
  'assets/images/find-pairs/13.png',
  'assets/images/find-pairs/14.png',
  'assets/images/find-pairs/1.png',
  'assets/images/find-pairs/2.png',
  'assets/images/find-pairs/3.png',
  'assets/images/find-pairs/4.png',
  'assets/images/find-pairs/5.png',
  'assets/images/find-pairs/6.png',
  'assets/images/find-pairs/7.png',
  'assets/images/find-pairs/8.png',
  'assets/images/find-pairs/9.png',
  'assets/images/find-pairs/10.png',
  'assets/images/find-pairs/11.png',
  'assets/images/find-pairs/12.png',
  'assets/images/find-pairs/13.png',
  'assets/images/find-pairs/14.png',
];

final List<LevelModel> findPairsRepository = [
  LevelModel(
    levelButton: 'assets/images/levels-buttons/1.png',
    number: 1,
    minutes: 3,
    seconds: 0,
    cardImages: elements,
  ),
  LevelModel(
    levelButton: 'assets/images/levels-buttons/2.png',
    number: 2,
    minutes: 3,
    seconds: 0,
    cardImages: elements,
  ),
  LevelModel(
    levelButton: 'assets/images/levels-buttons/3.png',
    number: 3,
    minutes: 3,
    seconds: 0,
    cardImages: elements,
  ),
  LevelModel(
    levelButton: 'assets/images/levels-buttons/4.png',
    number: 4,
    minutes: 2,
    seconds: 0,
    cardImages: elements,
  ),
  LevelModel(
    levelButton: 'assets/images/levels-buttons/5.png',
    number: 5,
    minutes: 2,
    seconds: 0,
    cardImages: elements,
  ),
  LevelModel(
    levelButton: 'assets/images/levels-buttons/6.png',
    number: 6,
    minutes: 1,
    seconds: 0,
    cardImages: elements,
  ),
  LevelModel(
    levelButton: 'assets/images/levels-buttons/7.png',
    number: 7,
    minutes: 1,
    seconds: 0,
    cardImages: elements,
  ),
  LevelModel(
    levelButton: 'assets/images/levels-buttons/8.png',
    number: 8,
    minutes: 1,
    seconds: 0,
    cardImages: elements,
  ),
  LevelModel(
    levelButton: 'assets/images/levels-buttons/9.png',
    number: 9,
    minutes: 1,
    seconds: 0,
    cardImages: elements,
  ),
];