name: sweet_bonanza_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  auto_route: ^8.0.3
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  flutter_countdown_timer: ^4.1.0
  stroke_text: ^0.0.2
  audioplayers: ^6.0.0
  
  flutter_inappwebview: ^6.0.0
  animated_flip_widget: ^0.0.2
  firebase_messaging: ^14.2.2
  firebase_core: ^2.21.0
  firebase_remote_config: ^4.3.3
  appsflyer_sdk:
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^9.8.0+1
  in_app_review: ^2.0.8
  overlay_support: ^2.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/elements/
    - assets/images/puzzle/
    - assets/images/puzzle/1/
    - assets/images/puzzle/2/
    - assets/images/puzzle/3/
    - assets/images/puzzle/4/
    - assets/images/puzzle/5/
    - assets/images/find-pairs/
    - assets/images/levels-buttons/

    - assets/audios/adventure-time.mp3


  fonts:
    - family: Blinker
      fonts:
        - asset: fonts/Blinker-Black.ttf
        - asset: fonts/Blinker-Bold.ttf
        - asset: fonts/Blinker-ExtraBold.ttf
        - asset: fonts/Blinker-Light.ttf
        - asset: fonts/Blinker-Regular.ttf
        - asset: fonts/Blinker-SemiBold.ttf


